version: '3.8'

services:
  rag-app:
    build: .
    ports:
      - "8000:8000"  # FastAPI backend
      - "8501:8501"  # Streamlit frontend
    volumes:
      - ./rag-backend:/app/backend
      - ./rag-streamlit:/app/frontend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped 