name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black
        pip install -r rag-backend/requirements.txt
        pip install -r rag-streamlit/requirements.txt

    - name: Lint with flake8
      run: |
        flake8 rag-backend rag-streamlit --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 rag-backend rag-streamlit --count --max-complexity=10 --max-line-length=127 --statistics

    - name: Check formatting with black
      run: |
        black --check rag-backend rag-streamlit

    - name: Run tests
      run: |
        pytest rag-backend/tests rag-streamlit/tests

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and test Docker image
      run: |
        docker build -t rag-app .
        docker run -d -p 8000:8000 -p 8501:8501 rag-app
        sleep 10
        curl -f http://localhost:8000/docs || exit 1
        curl -f http://localhost:8501 || exit 1 